DROP TABLE IF EXISTS satsang_comments;
DROP TABLE IF EXISTS sevaks;
DROP TABLE IF EXISTS smarans;
DROP TABLE IF EXISTS pranams;
ALTER TABLE reels DROP COLUMN IF EXISTS save_count;
ALTER TABLE reels DROP COLUMN IF EXISTS share_count;
ALTER TABLE users DROP COLUMN IF EXISTS comments_mode;
